"""
VERIFICATION of Section 1:
Partial order and causality (sec:partial_order).

Source file:
    1_partial_order.tex

This script verifies the mathematical content of the section as a standalone
order-theoretic layer over the already verified generative triangle.  It uses
the established level structure, generation rule, and predecessor decoding as
dependencies, then verifies the new claims about the causal relation, causal
cones, and causal diamonds.

Verified content
----------------
1. Causal reachability is the reflexive finite-chain relation generated by F:
       x <=_c x
   is represented by the empty chain.

2. Coordinate criterion:
   for x in L_n and y in L_{n+d},
       x <=_c y
   iff
       u_{n+d}(y) = s^d u_n(x) + D
   for a unique D satisfying
       0 <= D <= s^d - 1.

3. Poset properties:
   - reflexivity;
   - transitivity;
   - antisymmetry;
   - absence of nonzero causal cycles.

4. Transitive composition of digit coordinates:
       D_total = s^b D_1 + D_2
   for a depth-a chain followed by a depth-b chain.

5. Future cone slice:
       |C^+(x) cap L_{n+d}| = s^d
   for all d >= 0 in the checked finite windows.

6. Past cone slice:
       |C^-(x) cap L_{n-d}| = 1
   for 0 <= d <= n.

7. The past of any element is a unique linear ancestor chain from L_0.

8. Causal diamond:
       C(x,z) = C^+(x) cap C^-(z)
   is a linear chain whenever x <=_c z.  On each intermediate level it has
   exactly one element, even though the full future cone of x has s^ell
   elements on the same level.

9. Negative guards:
   - t(x) < t(y) alone does not imply x <=_c y;
   - distinct same-level points are incomparable;
   - distinct future branches from one point are incomparable at the same
     future level;
   - a noncausal pair is rejected by the causal-diamond constructor;
   - nonmatching predecessor/internal-state data do not regenerate the child;
   - invalid parameters, levels, states, points, and depths are rejected.

Expected result
---------------
All assertions pass and the final line reports successful completion.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from typing import Callable, Sequence

from sympy import simplify, symbols


class DomainError(ValueError):
    """Raised when a mathematical domain condition is violated."""


def expect_raises(expected_exception: type[BaseException] | tuple[type[BaseException], ...],
                  fn: Callable[[], object]) -> None:
    try:
        fn()
    except expected_exception:
        return
    raise AssertionError(f"Expected {expected_exception} was not raised")


def require_int(value: object, name: str) -> int:
    if not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")
    return value


def require_positive_int(value: object, name: str) -> int:
    value = require_int(value, name)
    if value < 1:
        raise DomainError(f"{name} must be a positive integer")
    return value


def require_nonnegative_int(value: object, name: str) -> int:
    value = require_int(value, name)
    if value < 0:
        raise DomainError(f"{name} must be a nonnegative integer")
    return value


def require_at_least(value: object, lower: int, name: str) -> int:
    value = require_int(value, name)
    if value < lower:
        raise DomainError(f"{name} must be at least {lower}")
    return value


@dataclass(frozen=True, slots=True)
class Model:
    m: int
    k: int
    s: int

    def __post_init__(self) -> None:
        require_positive_int(self.m, "m")
        require_at_least(self.k, 2, "k")
        require_at_least(self.s, 2, "s")

    @property
    def cA(self) -> int:
        return (self.s - 1) * self.m + 1 - self.k

    @property
    def S(self) -> tuple[int, ...]:
        return tuple(range(1, self.s + 1))

    @property
    def A(self) -> tuple[int, ...]:
        return tuple(range(self.m, self.m + self.k))

    def validate_state(self, sigma: object) -> int:
        sigma = require_int(sigma, "sigma")
        if not (1 <= sigma <= self.s):
            raise DomainError("sigma must belong to S={1,...,s}")
        return sigma

    def level_start(self, n: object) -> int:
        n = require_nonnegative_int(n, "n")
        numerator = self.k * (self.s**n - 1)
        denominator = self.s - 1
        assert numerator % denominator == 0
        return self.m + numerator // denominator

    def level_size(self, n: object) -> int:
        n = require_nonnegative_int(n, "n")
        return self.k * self.s**n

    def level_end(self, n: object) -> int:
        n = require_nonnegative_int(n, "n")
        return self.level_start(n) + self.level_size(n) - 1

    def level(self, n: object) -> tuple[int, ...]:
        n = require_nonnegative_int(n, "n")
        return tuple(range(self.level_start(n), self.level_end(n) + 1))

    def contains_level_point(self, x: object, n: object) -> bool:
        if not isinstance(x, int):
            return False
        n = require_nonnegative_int(n, "n")
        return self.level_start(n) <= x <= self.level_end(n)

    def require_level_point(self, x: object, n: object) -> int:
        x = require_positive_int(x, "x")
        if not self.contains_level_point(x, n):
            raise DomainError("x does not belong to the declared level")
        return x

    def position(self, x: object, n: object) -> int:
        x = self.require_level_point(x, n)
        n = require_nonnegative_int(n, "n")
        return x - self.level_start(n)

    def point_from_position(self, u: object, n: object) -> int:
        u = require_nonnegative_int(u, "u")
        n = require_nonnegative_int(n, "n")
        if u >= self.level_size(n):
            raise DomainError("u is outside the positional range of L_n")
        return self.level_start(n) + u

    def F(self, x: object, sigma: object) -> int:
        x = require_positive_int(x, "x")
        sigma = self.validate_state(sigma)
        return self.s * x + sigma - self.cA

    def local_preimage(self, y: object, previous_level: object) -> tuple[int, int]:
        previous_level = require_nonnegative_int(previous_level, "previous_level")
        y = self.require_level_point(y, previous_level + 1)
        child_position = self.position(y, previous_level + 1)
        parent_position = child_position // self.s
        sigma = child_position % self.s + 1
        parent = self.point_from_position(parent_position, previous_level)
        assert self.F(parent, sigma) == y
        return parent, sigma

    def immediate_predecessor(self, y: object, level_of_y: object) -> tuple[int, int]:
        level_of_y = require_nonnegative_int(level_of_y, "level_of_y")
        if level_of_y == 0:
            raise DomainError("level-zero elements have no predecessor inside T")
        return self.local_preimage(y, level_of_y - 1)

    def iterate(self, x: object, states: Sequence[int]) -> int:
        current = require_positive_int(x, "x")
        if not isinstance(states, tuple):
            raise TypeError("state sequence must be represented as a tuple")
        for sigma in states:
            current = self.F(current, sigma)
        return current

    def states_from_digit(self, D: object, depth: object) -> tuple[int, ...]:
        D = require_nonnegative_int(D, "D")
        depth = require_nonnegative_int(depth, "depth")
        if D >= self.s**depth:
            raise DomainError("D is outside the depth range")
        states: list[int] = []
        remaining = D
        for power in range(depth - 1, -1, -1):
            base_power = self.s**power
            digit = remaining // base_power
            remaining %= base_power
            states.append(digit + 1)
        return tuple(states)

    def digit_from_states(self, states: Sequence[int]) -> int:
        if not isinstance(states, tuple):
            raise TypeError("state sequence must be represented as a tuple")
        depth = len(states)
        total = 0
        for index, sigma in enumerate(states):
            sigma = self.validate_state(sigma)
            total += (sigma - 1) * self.s ** (depth - index - 1)
        return total

    def causal_leq(self, x: object, nx: object, y: object, ny: object) -> bool:
        nx = require_nonnegative_int(nx, "nx")
        ny = require_nonnegative_int(ny, "ny")
        if nx > ny:
            return False
        x = self.require_level_point(x, nx)
        y = self.require_level_point(y, ny)
        depth = ny - nx
        ux = self.position(x, nx)
        uy = self.position(y, ny)
        lower = self.s**depth * ux
        upper = lower + self.s**depth - 1
        return lower <= uy <= upper

    def causal_depth_and_digit(self, x: object, nx: object, y: object, ny: object) -> tuple[int, int]:
        if not self.causal_leq(x, nx, y, ny):
            raise DomainError("the pair is not causally related in the requested direction")
        nx = require_nonnegative_int(nx, "nx")
        ny = require_nonnegative_int(ny, "ny")
        depth = ny - nx
        ux = self.position(x, nx)
        uy = self.position(y, ny)
        D = uy - self.s**depth * ux
        assert 0 <= D <= self.s**depth - 1
        return depth, D

    def future_slice(self, x: object, n: object, depth: object) -> tuple[int, ...]:
        n = require_nonnegative_int(n, "n")
        depth = require_nonnegative_int(depth, "depth")
        x = self.require_level_point(x, n)
        ux = self.position(x, n)
        return tuple(
            self.point_from_position(self.s**depth * ux + D, n + depth)
            for D in range(self.s**depth)
        )

    def ancestor_at_level(self, x: object, n: object, target_level: object) -> int:
        n = require_nonnegative_int(n, "n")
        target_level = require_nonnegative_int(target_level, "target_level")
        if target_level > n:
            raise DomainError("target_level cannot exceed the point level")
        current = self.require_level_point(x, n)
        current_level = n
        while current_level > target_level:
            child = current
            parent, sigma = self.immediate_predecessor(child, current_level)
            assert self.F(parent, sigma) == child
            current = parent
            current_level -= 1
        return current

    def ancestor_chain(self, x: object, n: object) -> tuple[int, ...]:
        n = require_nonnegative_int(n, "n")
        return tuple(self.ancestor_at_level(x, n, level) for level in range(0, n + 1))

    def causal_diamond(self, x: object, nx: object, z: object, nz: object) -> tuple[int, ...]:
        nx = require_nonnegative_int(nx, "nx")
        nz = require_nonnegative_int(nz, "nz")
        if not self.causal_leq(x, nx, z, nz):
            raise DomainError("causal diamond requires x <=_c z")
        chain: list[int] = []
        for level in range(nx, nz + 1):
            y = self.ancestor_at_level(z, nz, level)
            assert self.causal_leq(x, nx, y, level)
            assert self.causal_leq(y, level, z, nz)
            chain.append(y)
        return tuple(chain)


def verify_symbolic_coordinate_formulas() -> None:
    print("\n=== Symbolic verification of causal composition and poset constraints ===")

    u, D1, D2, s, a, b = symbols("u D1 D2 s a b", integer=True, positive=True)

    intermediate = s**a * u + D1
    final = s**b * intermediate + D2
    composed = s ** (a + b) * u + (s**b * D1 + D2)
    assert simplify(final - composed) == 0

    # If D1 is in [0,s^a-1] and D2 in [0,s^b-1], then the composed digit lies
    # in [0,s^{a+b}-1].  The upper endpoint is checked symbolically.
    max_composed_digit = s**b * (s**a - 1) + (s**b - 1)
    assert simplify(max_composed_digit - (s ** (a + b) - 1)) == 0

    print("[OK] Digit-coordinate composition is symbolic")
    print("[OK] Depth-zero reachability is identity")
    print("[OK] Composed digits stay in the exact admissible range")


def verify_coordinate_criterion_and_generated_chains() -> None:
    print("\n=== Verification of coordinate criterion against generated chains ===")

    checked_chains = 0
    checked_decodings = 0
    checked_noncausal_pairs = 0

    models = (
        Model(1, 2, 2),
        Model(2, 3, 2),
        Model(3, 2, 3),
        Model(4, 3, 4),
    )

    for model in models:
        for n in range(0, 5):
            sample_positions = sorted({0, model.level_size(n) // 2, model.level_size(n) - 1})
            for u in sample_positions:
                x = model.point_from_position(u, n)

                # Empty chain.
                assert model.iterate(x, tuple()) == x
                assert model.causal_leq(x, n, x, n)
                depth0, D0 = model.causal_depth_and_digit(x, n, x, n)
                assert (depth0, D0) == (0, 0)

                for depth in range(1, 5):
                    for states in product(model.S, repeat=depth):
                        states = tuple(states)
                        y = model.iterate(x, states)
                        checked_chains += 1

                        assert model.contains_level_point(y, n + depth)
                        assert model.causal_leq(x, n, y, n + depth)

                        decoded_depth, D = model.causal_depth_and_digit(x, n, y, n + depth)
                        assert decoded_depth == depth
                        assert D == model.digit_from_states(states)
                        assert model.states_from_digit(D, depth) == states
                        checked_decodings += 1

                    # Pick a point just before or just after the descendant interval
                    # when possible; it must fail the coordinate criterion.
                    ux = model.position(x, n)
                    descendant_low = model.s**depth * ux
                    descendant_high = descendant_low + model.s**depth - 1
                    level_size = model.level_size(n + depth)

                    if descendant_low > 0:
                        y_bad = model.point_from_position(descendant_low - 1, n + depth)
                        assert not model.causal_leq(x, n, y_bad, n + depth)
                        checked_noncausal_pairs += 1

                    if descendant_high + 1 < level_size:
                        y_bad = model.point_from_position(descendant_high + 1, n + depth)
                        assert not model.causal_leq(x, n, y_bad, n + depth)
                        checked_noncausal_pairs += 1

    print(f"[OK] Checked {checked_chains} generated finite chains")
    print(f"[OK] Checked {checked_decodings} exact coordinate decodings")
    print(f"[OK] Checked {checked_noncausal_pairs} adjacent noncausal coordinate witnesses")


def verify_poset_axioms() -> None:
    print("\n=== Exact finite verification of poset axioms ===")

    checked_reflexive = 0
    checked_transitive = 0
    checked_antisymmetric = 0
    checked_no_cycles = 0

    models = (
        Model(1, 2, 2),
        Model(2, 3, 2),
        Model(3, 2, 3),
    )

    for model in models:
        max_level = 6

        for n in range(0, max_level + 1):
            for x in model.level(n)[:min(20, len(model.level(n)))]:
                checked_reflexive += 1
                assert model.causal_leq(x, n, x, n)

        for nx in range(0, 5):
            for first_depth in range(0, 4):
                ny = nx + first_depth
                for second_depth in range(0, 4):
                    nz = ny + second_depth
                    for x in model.level(nx)[:min(5, len(model.level(nx)))]:
                        for y in model.future_slice(x, nx, first_depth):
                            for z in model.future_slice(y, ny, second_depth):
                                checked_transitive += 1
                                assert model.causal_leq(x, nx, y, ny)
                                assert model.causal_leq(y, ny, z, nz)
                                assert model.causal_leq(x, nx, z, nz)

        for n in range(0, max_level + 1):
            sample = model.level(n)[:min(16, len(model.level(n)))]
            for x in sample:
                for y in sample:
                    checked_antisymmetric += 1
                    if model.causal_leq(x, n, y, n) and model.causal_leq(y, n, x, n):
                        assert x == y
                    elif x != y:
                        assert not model.causal_leq(x, n, y, n)
                        assert not model.causal_leq(y, n, x, n)

        for nx in range(0, 5):
            for depth in range(1, 4):
                ny = nx + depth
                for x in model.level(nx)[:min(6, len(model.level(nx)))]:
                    for y in model.future_slice(x, nx, depth):
                        checked_no_cycles += 1
                        assert model.causal_leq(x, nx, y, ny)
                        assert not model.causal_leq(y, ny, x, nx)

    print(f"[OK] Reflexivity checked on {checked_reflexive} points")
    print(f"[OK] Transitivity checked on {checked_transitive} composable triples")
    print(f"[OK] Antisymmetry checked on {checked_antisymmetric} same-level pairs")
    print(f"[OK] Nonzero cycle absence checked on {checked_no_cycles} causal pairs")


def verify_future_and_past_cone_cardinalities() -> None:
    print("\n=== Verification of future and past cone cardinalities ===")

    checked_future_slices = 0
    checked_future_points = 0
    checked_past_slices = 0
    checked_past_points = 0

    for model in (
        Model(1, 2, 2),
        Model(2, 4, 2),
        Model(5, 3, 3),
        Model(3, 2, 4),
    ):
        for n in range(0, 7):
            sample_positions = sorted({0, model.level_size(n) // 2, model.level_size(n) - 1})
            for u in sample_positions:
                x = model.point_from_position(u, n)

                for depth in range(0, 6):
                    future = model.future_slice(x, n, depth)
                    checked_future_slices += 1
                    checked_future_points += len(future)

                    assert len(future) == model.s**depth
                    assert len(set(future)) == model.s**depth
                    assert all(model.contains_level_point(y, n + depth) for y in future)
                    assert all(model.causal_leq(x, n, y, n + depth) for y in future)

                    positions = [model.position(y, n + depth) for y in future]
                    lower = model.s**depth * u
                    assert positions == list(range(lower, lower + model.s**depth))

                for steps_back in range(0, n + 1):
                    ancestor = model.ancestor_at_level(x, n, n - steps_back)
                    checked_past_slices += 1
                    checked_past_points += 1
                    assert model.contains_level_point(ancestor, n - steps_back)
                    assert model.causal_leq(ancestor, n - steps_back, x, n)

                    all_past_candidates = [
                        candidate for candidate in model.level(n - steps_back)
                        if model.causal_leq(candidate, n - steps_back, x, n)
                    ]
                    assert all_past_candidates == [ancestor]

    print(f"[OK] Checked {checked_future_slices} future cone slices")
    print(f"[OK] Checked {checked_future_points} future cone points")
    print(f"[OK] Checked {checked_past_slices} singleton past cone slices")
    print(f"[OK] Checked {checked_past_points} unique past cone elements")


def verify_unique_past_chains_and_causal_diamonds() -> None:
    print("\n=== Verification of unique past chains and causal diamonds ===")

    checked_chains = 0
    checked_chain_edges = 0
    checked_diamonds = 0
    checked_diamond_levels = 0
    checked_future_vs_diamond_guards = 0

    for model in (
        Model(1, 2, 2),
        Model(2, 3, 2),
        Model(3, 2, 3),
        Model(4, 2, 4),
    ):
        for nz in range(0, 7):
            sample_positions = sorted({0, model.level_size(nz) // 3, model.level_size(nz) - 1})
            for uz in sample_positions:
                z = model.point_from_position(uz, nz)
                full_chain = model.ancestor_chain(z, nz)
                checked_chains += 1

                assert len(full_chain) == nz + 1
                assert full_chain[-1] == z
                assert full_chain[0] in model.A

                for level, point in enumerate(full_chain):
                    assert model.contains_level_point(point, level)
                    assert model.causal_leq(point, level, z, nz)

                for level in range(1, nz + 1):
                    parent, sigma = model.immediate_predecessor(full_chain[level], level)
                    checked_chain_edges += 1
                    assert parent == full_chain[level - 1]
                    assert model.F(parent, sigma) == full_chain[level]

                # Any ancestor x of z defines a linear diamond from x to z.
                for nx in range(0, nz + 1):
                    x = full_chain[nx]
                    diamond = model.causal_diamond(x, nx, z, nz)
                    checked_diamonds += 1

                    assert len(diamond) == nz - nx + 1
                    assert diamond[0] == x
                    assert diamond[-1] == z

                    for offset, y in enumerate(diamond):
                        level = nx + offset
                        checked_diamond_levels += 1
                        assert model.contains_level_point(y, level)
                        assert model.causal_leq(x, nx, y, level)
                        assert model.causal_leq(y, level, z, nz)

                        candidates = [
                            candidate
                            for candidate in model.future_slice(x, nx, offset)
                            if model.causal_leq(candidate, level, z, nz)
                        ]
                        assert candidates == [y]

                        # Guard: full future slice generally branches, while the
                        # diamond stays singleton.  For offset>0 this distinction
                        # must be visible when s^offset>1.
                        if offset > 0:
                            future = model.future_slice(x, nx, offset)
                            assert len(future) == model.s**offset
                            assert len(future) > 1
                            assert len(candidates) == 1
                            checked_future_vs_diamond_guards += 1

    print(f"[OK] Checked {checked_chains} unique past chains")
    print(f"[OK] Checked {checked_chain_edges} predecessor edges in past chains")
    print(f"[OK] Checked {checked_diamonds} causal diamonds")
    print(f"[OK] Checked {checked_diamond_levels} singleton diamond level slices")
    print(f"[OK] Checked {checked_future_vs_diamond_guards} future-branching versus diamond-linearity guards")


def verify_branching_incomparability_and_time_nonconverse() -> None:
    print("\n=== Negative guards: branching, time order, and noncausal pairs ===")

    checked_branching = 0
    checked_same_level = 0
    checked_time_nonconverse = 0
    checked_noncausal_diamond_rejections = 0

    for model in (
        Model(1, 2, 2),
        Model(2, 3, 2),
        Model(3, 2, 3),
    ):
        for n in range(0, 5):
            sample_level = model.level(n)[:min(10, len(model.level(n)))]
            for x in sample_level:
                for y in sample_level:
                    checked_same_level += 1
                    if x == y:
                        assert model.causal_leq(x, n, y, n)
                    else:
                        assert not model.causal_leq(x, n, y, n)

        for n in range(0, 5):
            x = model.point_from_position(min(1, model.level_size(n) - 1), n)
            for depth in range(1, 4):
                future = model.future_slice(x, n, depth)
                if len(future) >= 2:
                    y1 = future[0]
                    y2 = future[-1]
                    checked_branching += 1
                    assert y1 != y2
                    assert model.causal_leq(x, n, y1, n + depth)
                    assert model.causal_leq(x, n, y2, n + depth)
                    assert not model.causal_leq(y1, n + depth, y2, n + depth)
                    assert not model.causal_leq(y2, n + depth, y1, n + depth)

        # Time order alone is insufficient.  Choose a point outside the
        # descendant interval at a later level.
        x = model.point_from_position(1, 1)
        depth = 2
        ux = model.position(x, 1)
        descendant_low = model.s**depth * ux
        if descendant_low > 0:
            y_bad = model.point_from_position(descendant_low - 1, 1 + depth)
            checked_time_nonconverse += 1
            assert 1 < 1 + depth
            assert not model.causal_leq(x, 1, y_bad, 1 + depth)
            expect_raises(DomainError, lambda model=model, x=x, y_bad=y_bad: model.causal_diamond(x, 1, y_bad, 1 + depth))
            checked_noncausal_diamond_rejections += 1

    print(f"[OK] Checked {checked_same_level} same-level comparability cases")
    print(f"[OK] Checked {checked_branching} branching incomparability witnesses")
    print(f"[OK] Checked {checked_time_nonconverse} time-order nonconverse witnesses")
    print(f"[OK] Checked {checked_noncausal_diamond_rejections} noncausal diamond rejections")


def verify_invalid_inputs_are_rejected() -> None:
    print("\n=== Negative domain tests ===")

    expect_raises(DomainError, lambda: Model(0, 2, 2))
    expect_raises(DomainError, lambda: Model(1, 1, 2))
    expect_raises(DomainError, lambda: Model(1, 2, 1))
    expect_raises(TypeError, lambda: Model(1.0, 2, 2))  # type: ignore[arg-type]
    expect_raises(TypeError, lambda: Model(1, 2.0, 2))  # type: ignore[arg-type]
    expect_raises(TypeError, lambda: Model(1, 2, 2.0))  # type: ignore[arg-type]

    model = Model(1, 2, 2)

    expect_raises(DomainError, lambda: model.level(-1))
    expect_raises(TypeError, lambda: model.level(1.5))  # type: ignore[arg-type]
    expect_raises(DomainError, lambda: model.require_level_point(1, 1))
    expect_raises(DomainError, lambda: model.require_level_point(1000, 0))
    expect_raises(DomainError, lambda: model.point_from_position(-1, 0))
    expect_raises(DomainError, lambda: model.point_from_position(model.level_size(2), 2))

    expect_raises(DomainError, lambda: model.F(1, 0))
    expect_raises(DomainError, lambda: model.F(1, 3))
    expect_raises(TypeError, lambda: model.F(1, 1.0))  # type: ignore[arg-type]

    expect_raises(DomainError, lambda: model.immediate_predecessor(model.m, 0))
    expect_raises(DomainError, lambda: model.local_preimage(model.m, 0))
    expect_raises(DomainError, lambda: model.local_preimage(model.level_start(2), 0))

    expect_raises(TypeError, lambda: model.iterate(1, [1, 2]))  # type: ignore[arg-type]
    expect_raises(DomainError, lambda: model.iterate(1, (1, 3)))
    expect_raises(DomainError, lambda: model.states_from_digit(-1, 2))
    expect_raises(DomainError, lambda: model.states_from_digit(4, 2))
    expect_raises(TypeError, lambda: model.causal_leq(1, 0.0, 1, 0))  # type: ignore[arg-type]

    x = model.point_from_position(1, 1)
    y = model.point_from_position(0, 3)
    expect_raises(DomainError, lambda: model.causal_depth_and_digit(x, 1, y, 3))
    expect_raises(DomainError, lambda: model.causal_diamond(x, 1, y, 3))
    expect_raises(DomainError, lambda: model.ancestor_at_level(x, 1, 2))

    print("[OK] Invalid parameters, coordinates, levels, states, chains, and noncausal requests are rejected")


def main() -> None:
    if not __debug__:
        raise RuntimeError(
            "This verification script must be run without Python optimization (-O), "
            "because assertions are part of the verification."
        )
    
    print("=== Verification of partial order and causality (sec:partial_order) ===")
    verify_symbolic_coordinate_formulas()
    verify_coordinate_criterion_and_generated_chains()
    verify_poset_axioms()
    verify_future_and_past_cone_cardinalities()
    verify_unique_past_chains_and_causal_diamonds()
    verify_branching_incomparability_and_time_nonconverse()
    verify_invalid_inputs_are_rejected()
    print("\n=== Partial-order verification completed successfully ===")


if __name__ == "__main__":
    main()
