"""
VERIFICATION of Section: Recursive macro-classes of causal microhistories
(sec:recursive-macro-classes).

This is a full mathematical verification block for
1_recursive_macro_classes.tex.

Scope
-----
This script verifies the new mathematical layer introduced in the file:
recursive compatibility of finite prefixes, macro-equivalence, finite
projections of macro-classes, frequency profiles of the normalized cumulative
spin coordinate barSigma_n, one-step recursive refinement, and branching under unlimited
continuation.

It intentionally does not re-prove the global bijectivity of F, the level
construction, the exact digit coordinate theorem, or the normalized-coordinate
spectrum theorem.  Those results are used only through their previously
verified formulas:

    D = sum_j (sigma_j - 1) s^{n-j},
    Delta rho = D / s^n,
    r_n = log_s(u_n + 1),
    eta(sigma) = sigma - (s+1)/2.

Verification safeguards
-----------------------------------------
1. Expected-failure tests are now sound.  The manual failure is raised outside
   the exception handler, so an invalid case is accepted only if the tested
   function itself rejects it.

2. The O(1) clause for the logarithmic coordinate is not replaced by equality
   of leading slopes.  Macro-equivalence stores an explicit O(1)-class label,
   and a separate symbolic block proves that equal leading slopes are not
   sufficient: examples with log(n) and sqrt(n) have the same slope but
   unbounded difference.

3. Branching is split into two checks:
   - actual pure continuations from a finite prefix are verified to land in
     different macro-classes;
   - a separate profile-level witness isolates the spin clause by keeping the
     rho-limit and O(1)-class fixed while changing only the spin limit.

4. Finite projections are checked with strict realization requirements.  The
   script also verifies that a proposed non-singleton projection generated by
   the usual ambiguous base-s expansions is not a valid macro-class projection
   under the full definition, because the spin-limit clause rejects it.  This
   prevents a false positive non-singleton test.

5. The centered spectrum is verified symbolically for arbitrary s >= 2:
   zero total sum, unit spacing, endpoint extrema, and B_s=(s-1)/2.

Terminology
-----------
Finite internal-state data are called prefixes or state sequences.  The script
avoids treating spin data as linguistic objects.

Expected result
---------------
All assertions pass and the final line reports successful completion.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import product
from math import log
from typing import Callable, Sequence

import sympy as sp


StateSequence = tuple[int, ...]


# ---------------------------------------------------------------------------
# Model dependencies already verified in earlier sections
# ---------------------------------------------------------------------------

def c_A(m: int, k: int, s: int) -> int:
    assert m >= 1
    assert k >= 2
    assert s >= 2
    return (s - 1) * m + 1 - k


def F(x: int, sigma: int, *, m: int, k: int, s: int) -> int:
    assert x >= 1
    assert 1 <= sigma <= s
    return s * x + sigma - c_A(m, k, s)


def level_start(n: int, *, m: int, k: int, s: int) -> int:
    assert n >= 0
    numerator = k * (s**n - 1)
    assert numerator % (s - 1) == 0
    return m + numerator // (s - 1)


def generate_x(a: int, sequence: Sequence[int], *, m: int, k: int, s: int) -> int:
    assert m <= a <= m + k - 1
    x = a
    for sigma in sequence:
        x = F(x, sigma, m=m, k=k, s=s)
    return x


def digit_coordinate(sequence: Sequence[int], s: int) -> int:
    n = len(sequence)
    D = 0
    for j, sigma in enumerate(sequence, start=1):
        assert 1 <= sigma <= s
        D += (sigma - 1) * s ** (n - j)
    return D


def u_from_sequence(a: int, sequence: Sequence[int], *, m: int, k: int, s: int) -> int:
    n = len(sequence)
    return (a - m) * s**n + digit_coordinate(sequence, s)


def normalized_delta_rho(sequence: Sequence[int], s: int) -> Fraction:
    n = len(sequence)
    assert n >= 1
    return Fraction(digit_coordinate(sequence, s), s**n)


def exact_r_exponent(a: int, sequence: Sequence[int], *, m: int, k: int, s: int) -> int:
    u = u_from_sequence(a, sequence, m=m, k=k, s=s)
    assert u >= 0
    return u + 1


def numeric_r(a: int, sequence: Sequence[int], *, m: int, k: int, s: int) -> float:
    return log(exact_r_exponent(a, sequence, m=m, k=k, s=s), s)


# ---------------------------------------------------------------------------
# Centered internal-state representation and frequency profiles
# ---------------------------------------------------------------------------

def eta(sigma: int, s: int) -> Fraction:
    assert 1 <= sigma <= s
    return Fraction(2 * sigma - s - 1, 2)


def B_s(s: int) -> Fraction:
    assert s >= 2
    return Fraction(s - 1, 2)


def counts_by_state(sequence: Sequence[int], s: int) -> dict[int, int]:
    assert all(1 <= sigma <= s for sigma in sequence)
    return {sigma: sum(1 for z in sequence if z == sigma) for sigma in range(1, s + 1)}


def frequencies_by_state(sequence: Sequence[int], s: int) -> dict[int, Fraction]:
    n = len(sequence)
    assert n >= 1
    counts = counts_by_state(sequence, s)
    return {sigma: Fraction(counts[sigma], n) for sigma in range(1, s + 1)}


def cumulative_spin(sequence: Sequence[int], s: int) -> Fraction:
    assert all(1 <= sigma <= s for sigma in sequence)
    return sum((eta(sigma, s) for sigma in sequence), Fraction(0))


def normalized_spin(sequence: Sequence[int], s: int) -> Fraction:
    n = len(sequence)
    assert n >= 1
    return cumulative_spin(sequence, s) / n


def frequency_profile_spin(sequence: Sequence[int], s: int) -> Fraction:
    freqs = frequencies_by_state(sequence, s)
    return sum((eta(sigma, s) * freqs[sigma] for sigma in range(1, s + 1)), Fraction(0))


# ---------------------------------------------------------------------------
# Infinite recursively compatible representatives
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EventuallyPeriodicFamily:
    """Infinite recursively compatible state family with fixed ancestor."""

    a: int
    finite_prefix: StateSequence
    period: StateSequence
    s: int

    def __post_init__(self) -> None:
        assert self.a >= 1
        assert self.s >= 2
        assert len(self.period) >= 1
        for sigma in self.finite_prefix + self.period:
            assert 1 <= sigma <= self.s

    def state_at(self, index_one_based: int) -> int:
        assert index_one_based >= 1
        L = len(self.finite_prefix)
        if index_one_based <= L:
            return self.finite_prefix[index_one_based - 1]
        return self.period[(index_one_based - L - 1) % len(self.period)]

    def prefix(self, n: int) -> StateSequence:
        assert n >= 1
        return tuple(self.state_at(i) for i in range(1, n + 1))

    def spin_limit(self) -> Fraction:
        return sum((eta(sigma, self.s) for sigma in self.period), Fraction(0)) / len(self.period)

    def rho_limit(self) -> Fraction:
        """Exact value of the infinite base-s expansion of Delta rho."""
        L = len(self.finite_prefix)
        p = len(self.period)

        finite_part = sum(
            Fraction(self.finite_prefix[j - 1] - 1, self.s**j)
            for j in range(1, L + 1)
        )
        period_block = sum(
            Fraction(self.period[t - 1], 1) / (self.s**t) - Fraction(1, self.s**t)
            for t in range(1, p + 1)
        )
        periodic_tail = Fraction(1, self.s**L) * period_block / (1 - Fraction(1, self.s**p))
        value = finite_part + periodic_tail
        assert Fraction(0) <= value <= Fraction(1)
        return value


@dataclass(frozen=True)
class AsymptoticMacroProfile:
    """Exact macro-equivalence quotient data.

    The r_O1_class field is an abstract class modulo bounded difference, not a
    leading slope.  Equal labels mean that the two logarithmic-coordinate
    profiles are known to differ by O(1).  Unequal labels mean that the script
    does not allow macro-equivalence through the r-clause.
    """

    rho_limit: Fraction
    r_O1_class: str
    spin_limit: Fraction



def profile_from_family(
    fam: EventuallyPeriodicFamily,
    *,
    r_O1_class: str = "generated-O1-class",
) -> AsymptoticMacroProfile:
    return AsymptoticMacroProfile(
        rho_limit=fam.rho_limit(),
        r_O1_class=r_O1_class,
        spin_limit=fam.spin_limit(),
    )


def macro_equivalent_profiles(p: AsymptoticMacroProfile, q: AsymptoticMacroProfile) -> bool:
    return (
        p.rho_limit == q.rho_limit
        and p.r_O1_class == q.r_O1_class
        and p.spin_limit == q.spin_limit
    )


# ---------------------------------------------------------------------------
# Finite macro-class projection
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FiniteMacroClass:
    representatives: tuple[EventuallyPeriodicFamily, ...]
    s: int
    a: int
    r_O1_class: str = "generated-O1-class"

    def __post_init__(self) -> None:
        assert len(self.representatives) >= 1
        profiles = []
        for rep in self.representatives:
            assert rep.s == self.s
            assert rep.a == self.a
            profiles.append(profile_from_family(rep, r_O1_class=self.r_O1_class))
        base = profiles[0]
        for profile in profiles[1:]:
            assert macro_equivalent_profiles(base, profile)

    def projection(self, n: int) -> set[tuple[int, StateSequence]]:
        assert n >= 1
        return {(self.a, rep.prefix(n)) for rep in self.representatives}


# ---------------------------------------------------------------------------
# Robust expected-failure helper
# ---------------------------------------------------------------------------

def expect_assertion(call: Callable[[], object], label: str) -> None:
    try:
        call()
    except AssertionError:
        return
    raise AssertionError(f"Expected rejection did not occur: {label}")


# ---------------------------------------------------------------------------
# Verification blocks
# ---------------------------------------------------------------------------

def verify_symbolic_centered_spectrum_general() -> None:
    print("\n=== Symbolic verification of the centered spectrum for arbitrary s >= 2 ===")

    q, j = sp.symbols("q j", integer=True, positive=True)
    eta_j = sp.Rational(1, 2) * (2 * j - q - 1)

    eta_sum = sp.summation(eta_j, (j, 1, q))
    assert sp.simplify(eta_sum) == 0

    eta_left = sp.simplify(eta_j.subs(j, 1))
    eta_right = sp.simplify(eta_j.subs(j, q))
    assert sp.simplify(eta_left + (q - 1) / 2) == 0
    assert sp.simplify(eta_right - (q - 1) / 2) == 0

    eta_step = sp.simplify(eta_j.subs(j, j + 1) - eta_j)
    assert eta_step == 1

    B_expr = sp.Rational(1, 2) * (q - 1)
    assert sp.simplify(abs(eta_left) - B_expr) == 0
    assert sp.simplify(abs(eta_right) - B_expr) == 0

    # Exact finite monotonicity check for representative arities confirms that
    # no interior state can exceed the endpoint absolute value.
    for s in range(2, 20):
        values = [eta(sigma, s) for sigma in range(1, s + 1)]
        assert sum(values, Fraction(0)) == 0
        assert values[0] == -B_s(s)
        assert values[-1] == B_s(s)
        assert all(values[i + 1] - values[i] == 1 for i in range(len(values) - 1))
        assert max(abs(v) for v in values) == B_s(s)

    print("[OK] sum_{sigma=1}^s eta(sigma)=0 symbolically for arbitrary s")
    print("[OK] endpoint extrema and B_s=(s-1)/2 are verified symbolically")
    print("[OK] finite monotonicity checks confirm that no interior state exceeds B_s")


def verify_symbolic_frequency_profile_identity() -> None:
    print("\n=== Symbolic verification of the frequency profile identity ===")

    q, j, n = sp.symbols("q j n", integer=True, positive=True)
    N = sp.IndexedBase("N")
    eta_j = sp.Rational(1, 2) * (2 * j - q - 1)

    Sigma_grouped = sp.Sum(eta_j * N[j], (j, 1, q))
    normalized_grouped = Sigma_grouped / n
    frequency_expression = sp.Sum(eta_j * (N[j] / n), (j, 1, q))
    assert sp.simplify(normalized_grouped - frequency_expression) == 0

    count_total = sp.Sum(N[j], (j, 1, q))
    frequency_total = sp.Sum(N[j] / n, (j, 1, q))
    assert sp.simplify(frequency_total.subs(n, count_total) - 1) == 0

    print("[OK] barSigma_n=sum_sigma eta(sigma) f_sigma is verified as a symbolic Sum identity")
    print("[OK] sum_sigma f_sigma=1 follows symbolically from n=sum_sigma N_sigma")


def verify_exhaustive_frequency_profile() -> None:
    print("\n=== Exhaustive exact verification of finite frequency profiles ===")

    total_sequences = 0
    for s, max_n in ((2, 12), (3, 8), (4, 6), (5, 5)):
        for n in range(1, max_n + 1):
            for sequence in product(range(1, s + 1), repeat=n):
                total_sequences += 1
                counts = counts_by_state(sequence, s)
                freqs = frequencies_by_state(sequence, s)

                assert sum(counts.values()) == n
                assert sum(freqs.values(), Fraction(0)) == 1
                assert all(Fraction(0) <= f <= Fraction(1) for f in freqs.values())

                Sigma = cumulative_spin(sequence, s)
                barSigma_n = normalized_spin(sequence, s)
                grouped = frequency_profile_spin(sequence, s)

                assert barSigma_n == grouped
                assert Sigma == sum(eta(sigma, s) * counts[sigma] for sigma in range(1, s + 1))
                assert -B_s(s) <= barSigma_n <= B_s(s)

    print(f"[OK] Exhaustively checked {total_sequences} finite state sequences")
    print("[OK] Counts, frequencies, cumulative spin and normalized spin agree exactly")


def verify_recursive_compatibility_and_normalized_coordinate() -> None:
    print("\n=== Verification of recursive compatibility and Delta rho ===")

    cases = [
        (1, 2, 2),
        (1, 3, 2),
        (2, 2, 3),
        (1, 4, 3),
        (3, 2, 4),
    ]

    checked = 0
    for m, k, s in cases:
        for a in range(m, m + k):
            families = [
                EventuallyPeriodicFamily(a=a, finite_prefix=(), period=(1,), s=s),
                EventuallyPeriodicFamily(a=a, finite_prefix=(), period=(s,), s=s),
                EventuallyPeriodicFamily(a=a, finite_prefix=(1, s), period=tuple(range(1, s + 1)), s=s),
                EventuallyPeriodicFamily(a=a, finite_prefix=(s,), period=tuple(reversed(range(1, s + 1))), s=s),
            ]

            for fam in families:
                previous_prefix: StateSequence | None = None
                for n in range(1, 10):
                    prefix = fam.prefix(n)
                    assert len(prefix) == n
                    assert all(1 <= sigma <= s for sigma in prefix)

                    if previous_prefix is not None:
                        assert prefix[:-1] == previous_prefix
                    previous_prefix = prefix

                    x = generate_x(a, prefix, m=m, k=k, s=s)
                    u_direct = x - level_start(n, m=m, k=k, s=s)
                    u_formula = u_from_sequence(a, prefix, m=m, k=k, s=s)
                    assert u_direct == u_formula

                    D = digit_coordinate(prefix, s)
                    rho = normalized_delta_rho(prefix, s)
                    assert rho == Fraction(D, s**n)
                    assert Fraction(0) <= rho < Fraction(1)

                    if all(sigma == 1 for sigma in prefix):
                        assert rho == 0
                    if all(sigma == s for sigma in prefix):
                        assert rho == Fraction(s**n - 1, s**n)

                    checked += 1

    print(f"[OK] Checked {checked} finite prefixes from recursively compatible families")
    print("[OK] Prefix recursion, generated x_chi^(n), u-coordinate and Delta rho match exactly")


def verify_macro_equivalence_relation() -> None:
    print("\n=== Verification of macro-equivalence as an equivalence relation ===")

    profiles = [
        AsymptoticMacroProfile(Fraction(0), "r-class-A", Fraction(-1, 2)),
        AsymptoticMacroProfile(Fraction(0), "r-class-A", Fraction(-1, 2)),
        AsymptoticMacroProfile(Fraction(1, 3), "r-class-B", Fraction(0)),
        AsymptoticMacroProfile(Fraction(1, 3), "r-class-B", Fraction(0)),
        AsymptoticMacroProfile(Fraction(1, 3), "r-class-C", Fraction(0)),
        AsymptoticMacroProfile(Fraction(1, 2), "r-class-B", Fraction(0)),
        AsymptoticMacroProfile(Fraction(1, 3), "r-class-B", Fraction(1, 2)),
    ]

    for p in profiles:
        assert macro_equivalent_profiles(p, p)

    for p in profiles:
        for q in profiles:
            assert macro_equivalent_profiles(p, q) == macro_equivalent_profiles(q, p)

    for p in profiles:
        for q in profiles:
            for r in profiles:
                if macro_equivalent_profiles(p, q) and macro_equivalent_profiles(q, r):
                    assert macro_equivalent_profiles(p, r)

    base = AsymptoticMacroProfile(Fraction(1, 3), "r-class-B", Fraction(0))
    fail_rho = AsymptoticMacroProfile(Fraction(1, 2), "r-class-B", Fraction(0))
    fail_r = AsymptoticMacroProfile(Fraction(1, 3), "different-O1-class", Fraction(0))
    fail_spin = AsymptoticMacroProfile(Fraction(1, 3), "r-class-B", Fraction(1, 2))

    assert not macro_equivalent_profiles(base, fail_rho)
    assert not macro_equivalent_profiles(base, fail_r)
    assert not macro_equivalent_profiles(base, fail_spin)

    print("[OK] Reflexivity, symmetry and transitivity verified for the three-clause quotient")
    print("[OK] Negative witnesses isolate rho, O(1)-class and spin-limit failures")


def verify_logarithmic_O1_clause_without_slope_substitution() -> None:
    print("\n=== Verification that the O(1) clause is not slope equality ===")

    n = sp.symbols("n", positive=True, integer=True)
    r_base = n
    r_bounded = n + sp.Rational(7, 5)
    r_log = n + sp.log(n)
    r_sqrt = n + sp.sqrt(n)
    r_different_slope = 2 * n

    for expr in (r_base, r_bounded, r_log, r_sqrt):
        assert sp.simplify(sp.limit(expr / n, n, sp.oo) - 1) == 0

    assert sp.limit(abs(r_base - r_bounded), n, sp.oo) == sp.Rational(7, 5)
    assert sp.limit(r_log - r_base, n, sp.oo) == sp.oo
    assert sp.limit(r_sqrt - r_base, n, sp.oo) == sp.oo
    assert sp.limit(abs(r_different_slope - r_base), n, sp.oo) == sp.oo

    # Exact finite growth witnesses distinguish bounded from unbounded same-slope
    # differences without relying on floating point arithmetic.
    bounded_diffs = [abs(Fraction(N) - (Fraction(N) + Fraction(7, 5))) for N in range(1, 200)]
    assert len(set(bounded_diffs)) == 1

    sqrt_diffs = [int(sp.sqrt(N)) for N in (10**2, 10**4, 10**6)]
    assert sqrt_diffs[0] < sqrt_diffs[1] < sqrt_diffs[2]

    print("[OK] Equal leading slope is verified to be insufficient for the O(1) clause")
    print("[OK] log(n) and sqrt(n) examples have the same slope but unbounded r-difference")
    print("[OK] The macro relation uses an explicit O(1)-class, not r_slope equality")


def verify_finite_projection_macroclass() -> None:
    print("\n=== Verification of finite projections P_n of a macro-class ===")

    s = 3
    a = 1
    reps = (
        EventuallyPeriodicFamily(a=a, finite_prefix=(), period=(2,), s=s),
        EventuallyPeriodicFamily(a=a, finite_prefix=(), period=(2, 2), s=s),
        EventuallyPeriodicFamily(a=a, finite_prefix=(2,), period=(2,), s=s),
    )

    macroclass = FiniteMacroClass(representatives=reps, s=s, a=a)

    previous_projection: set[tuple[int, StateSequence]] | None = None
    for n in range(1, 12):
        P_n = macroclass.projection(n)
        assert len(P_n) == 1
        for ancestor, prefix in P_n:
            assert ancestor == a
            assert len(prefix) == n
            assert all(1 <= sigma <= s for sigma in prefix)
            assert prefix == (2,) * n

        if previous_projection is not None:
            projected_down = {(ancestor, prefix[:-1]) for ancestor, prefix in P_n}
            assert projected_down == previous_projection

        previous_projection = P_n

    print("[OK] P_n contains exactly realized length-n prefixes of valid representatives")
    print("[OK] Fixed ancestor, length condition and prefix-consistency P_{n+1}->P_n hold")


def verify_non_singleton_projection_obstruction() -> None:
    print("\n=== Guard against false non-singleton projection tests ===")

    # Base-2 ambiguous expansions represent the same rho-limit:
    #   0.1000... = 0.0111...
    # However, the spin limits are -1/2 and +1/2 after the finite offset, so
    # they are not in the same macro-class under the full definition.
    left = EventuallyPeriodicFamily(a=1, finite_prefix=(2,), period=(1,), s=2)
    right = EventuallyPeriodicFamily(a=1, finite_prefix=(1,), period=(2,), s=2)

    p_left = profile_from_family(left)
    p_right = profile_from_family(right)

    assert p_left.rho_limit == p_right.rho_limit == Fraction(1, 2)
    assert p_left.r_O1_class == p_right.r_O1_class
    assert p_left.spin_limit == Fraction(-1, 2)
    assert p_right.spin_limit == Fraction(1, 2)
    assert not macro_equivalent_profiles(p_left, p_right)

    expect_assertion(
        lambda: FiniteMacroClass(representatives=(left, right), s=2, a=1),
        "ambiguous rho representatives with different spin limits must not form one macro-class",
    )

    # Exhaustive finite search over small eventually periodic representatives:
    # whenever the full macro-profile agrees, the tested projections remain
    # singleton.  This supports the point that exact Delta-rho plus spin-limit
    # clauses make a genuine multi-prefix projection highly constrained.
    for s in (2, 3):
        candidates: list[EventuallyPeriodicFamily] = []
        alphabet = range(1, s + 1)
        for prefix_len in range(0, 3):
            for period_len in range(1, 3):
                for finite_prefix in product(alphabet, repeat=prefix_len):
                    for period in product(alphabet, repeat=period_len):
                        candidates.append(
                            EventuallyPeriodicFamily(
                                a=1,
                                finite_prefix=tuple(finite_prefix),
                                period=tuple(period),
                                s=s,
                            )
                        )

        classes: dict[AsymptoticMacroProfile, list[EventuallyPeriodicFamily]] = {}
        for fam in candidates:
            classes.setdefault(profile_from_family(fam), []).append(fam)

        for reps in classes.values():
            if len(reps) < 2:
                continue
            macroclass = FiniteMacroClass(representatives=tuple(reps), s=s, a=1)
            for n in range(1, 5):
                projection = macroclass.projection(n)
                assert len(projection) == 1

    print("[OK] Ambiguous rho equality alone is rejected when the spin-limit clause fails")
    print("[OK] Small exhaustive periodic search found no false multi-prefix macro-class projection")


def verify_one_step_refinement_formula_and_bound() -> None:
    print("\n=== Verification of one-step refinement of normalized spin ===")

    n, Sigma_n, eta_new = sp.symbols("n Sigma_n eta_new", positive=True)
    barSigma_np1 = (Sigma_n + eta_new) / (n + 1)
    barSigma_n_expr = Sigma_n / n
    expected_delta = (n * eta_new - Sigma_n) / (n * (n + 1))
    assert sp.simplify((barSigma_np1 - barSigma_n_expr) - expected_delta) == 0

    total_extensions = 0
    for s, max_n in ((2, 12), (3, 8), (4, 6), (5, 5), (6, 4)):
        B = B_s(s)
        for n_int in range(1, max_n + 1):
            bound = Fraction(2 * B, n_int + 1)

            for sequence in product(range(1, s + 1), repeat=n_int):
                Sigma = cumulative_spin(sequence, s)
                old_s = Sigma / n_int
                assert abs(Sigma) <= n_int * B

                for sigma_next in range(1, s + 1):
                    extended = sequence + (sigma_next,)
                    direct_delta = normalized_spin(extended, s) - old_s
                    formula_delta = Fraction(n_int * eta(sigma_next, s) - Sigma, n_int * (n_int + 1))

                    assert direct_delta == formula_delta
                    assert abs(direct_delta) <= bound
                    total_extensions += 1

            all_min_then_max = (1,) * n_int + (s,)
            all_max_then_min = (s,) * n_int + (1,)
            delta_1 = normalized_spin(all_min_then_max, s) - normalized_spin((1,) * n_int, s)
            delta_2 = normalized_spin(all_max_then_min, s) - normalized_spin((s,) * n_int, s)
            assert abs(delta_1) == bound
            assert abs(delta_2) == bound

            if s == 2:
                assert bound == Fraction(1, n_int + 1)

    print("[OK] Symbolically derived the exact one-step refinement formula")
    print(f"[OK] Exhaustively checked {total_extensions} one-step extensions")
    print("[OK] The bound 2B_s/(n+1) is satisfied and sharp")


def verify_refinement_branching_actual_continuations() -> None:
    print("\n=== Verification of branching under unlimited recursive continuation ===")

    checked = 0
    for s in range(2, 7):
        for prefix_length in range(0, 5):
            for prefix in product(range(1, s + 1), repeat=prefix_length):
                for next_state in range(1, s + 1):
                    refined_prefix = tuple(prefix) + (next_state,)

                    left = EventuallyPeriodicFamily(a=1, finite_prefix=refined_prefix, period=(1,), s=s)
                    right = EventuallyPeriodicFamily(a=1, finite_prefix=refined_prefix, period=(s,), s=s)

                    assert left.prefix(len(refined_prefix)) == refined_prefix
                    assert right.prefix(len(refined_prefix)) == refined_prefix

                    assert left.spin_limit() == eta(1, s)
                    assert right.spin_limit() == eta(s, s)
                    assert left.spin_limit() != right.spin_limit()

                    p_left = profile_from_family(left)
                    p_right = profile_from_family(right)
                    assert not macro_equivalent_profiles(p_left, p_right)

                    if s == 2:
                        assert left.spin_limit() == Fraction(-1, 2)
                        assert right.spin_limit() == Fraction(1, 2)

                    checked += 1

    print(f"[OK] Checked {checked} refined prefixes across s=2,...,6")
    print("[OK] Pure endpoint continuations have distinct spin limits and different macro-profiles")


def verify_spin_clause_isolated_profile_witness() -> None:
    print("\n=== Isolated witness for the spin clause of macro-equivalence ===")

    common_rho = Fraction(3, 7)
    common_r = "same-O1-class"
    p = AsymptoticMacroProfile(common_rho, common_r, Fraction(-1, 3))
    q = AsymptoticMacroProfile(common_rho, common_r, Fraction(1, 6))

    assert p.rho_limit == q.rho_limit
    assert p.r_O1_class == q.r_O1_class
    assert p.spin_limit != q.spin_limit
    assert not macro_equivalent_profiles(p, q)

    print("[OK] rho-limit and O(1)-class are fixed while only the spin limit changes")
    print("[OK] Macro-equivalence fails solely through the spin clause in this profile witness")


def verify_normalized_coordinate_refinement_dependency() -> None:
    print("\n=== Dependency check: finite use of normalized coordinate refinement ===")

    for s in range(2, 7):
        for n in range(1, 7):
            grid = {normalized_delta_rho(sequence, s) for sequence in product(range(1, s + 1), repeat=n)}
            expected_grid = {Fraction(D, s**n) for D in range(0, s**n)}
            assert grid == expected_grid
            assert min(grid) == 0
            assert max(grid) == Fraction(s**n - 1, s**n)

            sorted_grid = sorted(grid)
            if len(sorted_grid) > 1:
                spacings = {sorted_grid[i + 1] - sorted_grid[i] for i in range(len(sorted_grid) - 1)}
                assert spacings == {Fraction(1, s**n)}

            for sequence in product(range(1, s + 1), repeat=n):
                for sigma_next in range(1, s + 1):
                    rho_n = normalized_delta_rho(sequence, s)
                    rho_np1 = normalized_delta_rho(sequence + (sigma_next,), s)
                    expected = rho_n + Fraction(sigma_next - 1, s ** (n + 1))
                    assert rho_np1 == expected

    print("[OK] The finite coordinate spectrum used by macro-classes is exactly {D/s^n}")
    print("[OK] Recursive refinement appends one internal state at scale s^{-(n+1)}")


def verify_domain_and_failure_cases() -> None:
    print("\n=== Domain and failure-case verification ===")

    expect_assertion(lambda: normalized_spin((), 2), "normalized_spin must reject n=0")
    expect_assertion(lambda: normalized_delta_rho((), 2), "Delta rho must reject n=0")

    fam_a1 = EventuallyPeriodicFamily(a=1, finite_prefix=(), period=(1,), s=2)
    fam_a2 = EventuallyPeriodicFamily(a=2, finite_prefix=(), period=(1,), s=2)
    assert fam_a1.a != fam_a2.a

    expect_assertion(
        lambda: FiniteMacroClass(representatives=(fam_a1, fam_a2), s=2, a=1),
        "macro-class representatives must have the fixed ancestor a",
    )

    expect_assertion(
        lambda: EventuallyPeriodicFamily(a=1, finite_prefix=(1,), period=(3,), s=2),
        "representative must reject states outside S",
    )

    expect_assertion(
        lambda: F(1, 0, m=1, k=2, s=2),
        "F must reject state 0 outside S",
    )

    expect_assertion(
        lambda: F(1, 3, m=1, k=2, s=2),
        "F must reject state s+1 outside S",
    )

    print("[OK] Expected-failure checks are structurally sound")
    print("[OK] Empty prefixes, wrong ancestors and invalid states are rejected")


def main() -> None:
    if not __debug__:
        raise RuntimeError(
            "This verification script must be run without Python optimization (-O), "
            "because assertions are part of the verification."
        )
    
    print("=== Verification of recursive macro-classes of causal microhistories ===")
    verify_symbolic_centered_spectrum_general()
    verify_symbolic_frequency_profile_identity()
    verify_exhaustive_frequency_profile()
    verify_recursive_compatibility_and_normalized_coordinate()
    verify_macro_equivalence_relation()
    verify_logarithmic_O1_clause_without_slope_substitution()
    verify_finite_projection_macroclass()
    verify_non_singleton_projection_obstruction()
    verify_one_step_refinement_formula_and_bound()
    verify_refinement_branching_actual_continuations()
    verify_spin_clause_isolated_profile_witness()
    verify_normalized_coordinate_refinement_dependency()
    verify_domain_and_failure_cases()
    print("\n=== recursive_macro_classes verification completed successfully ===")


if __name__ == "__main__":
    main()
