"""
VERIFICATION of Section: Causal localization and containment of stable
recursive structures (sec:causal-localization-stable-structures).

This script provides a full mathematical verification block for
4_causal_localization_stable_structures.tex.  It does not re-verify the earlier
construction of the generative triangle, recursive macroclasses, controlled
characteristics, or recursive stability.  Those results are used only as
established dependencies.  The present block verifies the new layer introduced
in this section: geometric spread, weak and strong causal localization, causal
containment under unbounded recursive refinement, loss of localization,
localized recursively stable structures, and the separation between geometric
localization and internal-state organization.

Verified content
----------------
1. Finite geometric profiles:
      Delta-rho_n(P) = {Delta-rho^(n)(prefix) : prefix in P_n},
      R_n(P)         = {r_n(x_prefix^(n)) : prefix in P_n}.
   The script checks that both profiles are exact set-valued images of the
   finite projection and that their diameters are the exact finite suprema of
   pairwise distances.

2. Exact normalized causal-coordinate spread:
   for finite internal-state prefixes with base s, the digit coordinate D and
   Delta-rho = D/s^n are computed exactly as rational numbers.  The diameter
   D_{rho,n}(P) is checked against max(Delta-rho)-min(Delta-rho) and against
   an exhaustive pairwise supremum.

3. Exact logarithmic-coordinate spread:
   R_n(P) is represented by the monotone logarithmic coordinate log_s(D+1).
   The diameter D_{r,n}(P) is verified symbolically as
      log_s((D_max + 1)/(D_min + 1))
   whenever the finite projection is nonempty.

4. Weak causal localization:
      limsup D_{rho,n}(P) < 1  OR  D_{r,n}(P) = O(1).
   The disjunctive nature of the definition is verified by positive witnesses
   satisfying only the first clause, only the second clause, or both clauses.
   Negative witnesses verify that both failures are required for non-locality.

5. Strong causal localization:
      D_{rho,n}(P) -> 0  AND  D_{r,n}(P) = O(1).
   The script verifies that strong localization implies weak localization, and
   that the converse fails by exact asymptotic witnesses.

6. No replacement of O(1) by equal leading slope:
   symbolic counterexamples r_2(n)-r_1(n)=log(n) and sqrt(n) are checked to be
   unbounded despite having the same leading linear slope.  This prevents the
   common but invalid replacement of bounded logarithmic spread by equal slope.

7. Causal containment:
   a continuation is accepted only if every later finite projection is a
   one-step recursive refinement of the preceding projection and all shifted
   tails remain in the requested weak or strong localization regime.  The
   script verifies positive contained towers, incompatible towers, and towers
   whose geometry escapes localization after refinement.

8. Loss of localization:
   under the intrinsic bound 0 <= D_{rho,n} <= 1, the negation of weak
   localization is verified as
      limsup D_{rho,n}(P) = 1  AND  D_{r,n}(P) is not O(1).
   Separate witnesses cover full cone filling, unbounded logarithmic spread,
   oscillatory failure with limsup equal to one, and geometrically incompatible
   refinement branches.

9. Localized recursively stable structure:
   the final notion is checked as a genuine conjunction of recursive stability,
   geometric localization, and causal containment.  Negative tests show that
   dropping any one of the three assumptions is detected.

10. Emergent boundary as loss of recursive compatibility:
    admissible continuations are generated by an organization-dependent
    geometric predicate.  The boundary is verified to be the exact complement
    of recursively compatible admissible refinement, not a fixed external cut.

11. Geometric localization does not by itself fix internal-state organization:
    two structures with identical geometric localization data but distinct or
    nonconvergent internal-state frequency data are accepted by the geometric
    localization predicate and rejected by an internal-organization predicate.

Expected result
---------------
All assertions pass and the final line reports successful completion.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import product
from typing import Callable, Iterable, Sequence

from sympy import Rational, Symbol, oo, simplify, limit, log, sqrt


# ---------------------------------------------------------------------------
# Exact finite-prefix geometry
# ---------------------------------------------------------------------------


def expect_raises(expected_exception: type[BaseException], thunk: Callable[[], object], label: str) -> None:
    """Fail unless thunk raises expected_exception directly."""
    try:
        thunk()
    except expected_exception:
        return
    raise AssertionError(f"Expected {expected_exception.__name__} was not raised: {label}")


@dataclass(frozen=True)
class StatePrefix:
    """Finite internal-state prefix over S={1,...,s}."""

    states: tuple[int, ...]
    s: int

    def __post_init__(self) -> None:
        if self.s < 2:
            raise ValueError("The base s must satisfy s >= 2")
        if len(self.states) == 0:
            raise ValueError("A finite prefix used for geometric coordinates must be nonempty")
        if any(state < 1 or state > self.s for state in self.states):
            raise ValueError("Every internal state must lie in {1,...,s}")

    @property
    def level(self) -> int:
        return len(self.states)

    @property
    def digit_coordinate(self) -> int:
        # The zero-based digit is state-1.  The first state is the most
        # significant digit of the causal-layer coordinate.
        total = 0
        n = self.level
        for index, state in enumerate(self.states):
            total += (state - 1) * self.s ** (n - index - 1)
        return total

    @property
    def delta_rho(self) -> Fraction:
        return Fraction(self.digit_coordinate, self.s ** self.level)

    @property
    def r_expr(self):
        return log(self.digit_coordinate + 1) / log(self.s)

    def parent(self) -> "StatePrefix | None":
        if self.level == 1:
            return None
        return StatePrefix(self.states[:-1], self.s)

    def extends_by_one(self, previous: "StatePrefix") -> bool:
        return self.s == previous.s and self.level == previous.level + 1 and self.states[:-1] == previous.states


def finite_projection(prefixes: Iterable[StatePrefix]) -> tuple[StatePrefix, ...]:
    projection = tuple(prefixes)
    if not projection:
        raise ValueError("Finite projection must be nonempty")
    base = projection[0].s
    level = projection[0].level
    if any(p.s != base for p in projection):
        raise ValueError("All prefixes in one projection must use the same base s")
    if any(p.level != level for p in projection):
        raise ValueError("All prefixes in one projection must belong to the same level")
    # remove duplicates while preserving deterministic order
    seen: set[tuple[int, ...]] = set()
    unique: list[StatePrefix] = []
    for p in projection:
        if p.states not in seen:
            seen.add(p.states)
            unique.append(p)
    return tuple(unique)


def delta_rho_profile(projection: Sequence[StatePrefix]) -> set[Fraction]:
    return {p.delta_rho for p in finite_projection(projection)}


def r_profile(projection: Sequence[StatePrefix]):
    return {p.r_expr for p in finite_projection(projection)}


def pairwise_fraction_diameter(values: Iterable[Fraction]) -> Fraction:
    vals = tuple(values)
    if not vals:
        raise ValueError("Diameter of an empty set is undefined")
    return max(abs(a - b) for a in vals for b in vals)


def delta_rho_diameter(projection: Sequence[StatePrefix]) -> Fraction:
    values = delta_rho_profile(projection)
    return pairwise_fraction_diameter(values)


def r_diameter_expr(projection: Sequence[StatePrefix]):
    proj = finite_projection(projection)
    digits = [p.digit_coordinate for p in proj]
    s = proj[0].s
    d_min = min(digits)
    d_max = max(digits)
    return log(Rational(d_max + 1, d_min + 1)) / log(s)


def all_prefixes(s: int, n: int) -> tuple[StatePrefix, ...]:
    return tuple(StatePrefix(tuple(states), s) for states in product(range(1, s + 1), repeat=n))


# ---------------------------------------------------------------------------
# Asymptotic localization profiles
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AsymptoticGeometry:
    name: str
    rho_diameter: Callable[[int], Fraction]
    r_diameter_expr: Callable[[Symbol], object]
    rho_limsup: Fraction
    rho_limit: Fraction | None
    r_is_O1: bool

    def weakly_localized(self) -> bool:
        return self.rho_limsup < 1 or self.r_is_O1

    def strongly_localized(self) -> bool:
        return self.rho_limit == 0 and self.r_is_O1

    def not_localized(self) -> bool:
        # Since D_{rho,n} is a diameter inside [0,1), the only possible failure
        # of limsup < 1 is limsup = 1.
        return self.rho_limsup == 1 and not self.r_is_O1

    def shifted(self, k: int) -> "AsymptoticGeometry":
        if k < 0:
            raise ValueError("Tail shift must be nonnegative")

        def shifted_rho(n: int) -> Fraction:
            return self.rho_diameter(n + k)

        return AsymptoticGeometry(
            name=f"{self.name}[tail+{k}]",
            rho_diameter=shifted_rho,
            r_diameter_expr=lambda n, self=self, k=k: self.r_diameter_expr(n + k),
            rho_limsup=self.rho_limsup,
            rho_limit=self.rho_limit,
            r_is_O1=self.r_is_O1,
        )


STRONG_GEOMETRY = AsymptoticGeometry(
    name="strong: D_rho=1/n, D_r=3",
    rho_diameter=lambda n: Fraction(1, n),
    r_diameter_expr=lambda n: Rational(3),
    rho_limsup=Fraction(0),
    rho_limit=Fraction(0),
    r_is_O1=True,
)

WEAK_BY_RHO_ONLY = AsymptoticGeometry(
    name="weak by rho only: D_rho=1/2, D_r=n",
    rho_diameter=lambda n: Fraction(1, 2),
    r_diameter_expr=lambda n: n,
    rho_limsup=Fraction(1, 2),
    rho_limit=Fraction(1, 2),
    r_is_O1=False,
)

WEAK_BY_R_ONLY = AsymptoticGeometry(
    name="weak by r only: D_rho=1-1/n, D_r=2",
    rho_diameter=lambda n: Fraction(n - 1, n),
    r_diameter_expr=lambda n: Rational(2),
    rho_limsup=Fraction(1),
    rho_limit=Fraction(1),
    r_is_O1=True,
)

NONLOCAL_LOG = AsymptoticGeometry(
    name="nonlocal: D_rho=1-1/n, D_r=log(n)",
    rho_diameter=lambda n: Fraction(n - 1, n),
    r_diameter_expr=lambda n: log(n),
    rho_limsup=Fraction(1),
    rho_limit=Fraction(1),
    r_is_O1=False,
)

NONLOCAL_SQRT = AsymptoticGeometry(
    name="nonlocal: D_rho=1-1/n, D_r=sqrt(n)",
    rho_diameter=lambda n: Fraction(n - 1, n),
    r_diameter_expr=lambda n: sqrt(n),
    rho_limsup=Fraction(1),
    rho_limit=Fraction(1),
    r_is_O1=False,
)

OSCILLATORY_NONLOCAL = AsymptoticGeometry(
    name="oscillatory nonlocal: limsup D_rho=1, D_r=sqrt(n)",
    rho_diameter=lambda n: Fraction(1, 1) if n % 2 == 0 else Fraction(1, 2),
    r_diameter_expr=lambda n: sqrt(n),
    rho_limsup=Fraction(1),
    rho_limit=None,
    r_is_O1=False,
)


# ---------------------------------------------------------------------------
# Recursive refinement towers and causal containment
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RefinementTower:
    name: str
    projections: tuple[tuple[StatePrefix, ...], ...]
    geometry: AsymptoticGeometry

    def __post_init__(self) -> None:
        if not self.projections:
            raise ValueError("A refinement tower must contain at least one projection")
        for projection in self.projections:
            finite_projection(projection)

    def is_recursively_compatible(self) -> bool:
        for previous, current in zip(self.projections, self.projections[1:]):
            previous_set = set(previous)
            for prefix in current:
                parent = prefix.parent()
                if parent not in previous_set:
                    return False
        return True

    def tail_geometry(self, k: int) -> AsymptoticGeometry:
        return self.geometry.shifted(k)


def contained_in_mode(towers: Sequence[RefinementTower], mode: str, max_tail_shift_checked: int = 8) -> bool:
    if mode not in {"weak", "strong"}:
        raise ValueError("mode must be 'weak' or 'strong'")
    if not towers:
        raise ValueError("Causal containment cannot be verified from an empty family of continuations")
    for tower in towers:
        if not tower.is_recursively_compatible():
            return False
        for k in range(max_tail_shift_checked + 1):
            tail = tower.tail_geometry(k)
            if mode == "weak" and not tail.weakly_localized():
                return False
            if mode == "strong" and not tail.strongly_localized():
                return False
    return True


def make_refinement_tower(base: int = 2, height: int = 5, branch_state: int = 1, geometry: AsymptoticGeometry = STRONG_GEOMETRY) -> RefinementTower:
    projections: list[tuple[StatePrefix, ...]] = []
    for n in range(1, height + 1):
        prefix = StatePrefix(tuple([branch_state] * n), base)
        projections.append((prefix,))
    return RefinementTower("single compatible refinement tower", tuple(projections), geometry)


def make_incompatible_tower() -> RefinementTower:
    return RefinementTower(
        "incompatible branch jump",
        (
            (StatePrefix((1,), 2),),
            (StatePrefix((2, 1), 2),),  # parent is (2,), not the previous prefix (1,)
        ),
        STRONG_GEOMETRY,
    )


# ---------------------------------------------------------------------------
# Stable/localized structure records
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CandidateStructure:
    name: str
    recursively_stable: bool
    geometry: AsymptoticGeometry
    contained: bool

    def localized_recursively_stable(self, mode: str = "weak") -> bool:
        if mode == "weak":
            localized = self.geometry.weakly_localized()
        elif mode == "strong":
            localized = self.geometry.strongly_localized()
        else:
            raise ValueError("mode must be 'weak' or 'strong'")
        return self.recursively_stable and localized and self.contained


@dataclass(frozen=True)
class InternalOrganization:
    name: str
    geometric_data: AsymptoticGeometry
    internal_frequency_limit: Fraction | None
    internal_frequency_convergent: bool

    def passes_geometric_localization(self) -> bool:
        return self.geometric_data.weakly_localized()

    def passes_internal_organization(self) -> bool:
        return self.internal_frequency_convergent and self.internal_frequency_limit is not None


# ---------------------------------------------------------------------------
# Verification blocks
# ---------------------------------------------------------------------------


def verify_finite_geometric_profiles_and_diameters() -> None:
    print("\n=== Finite geometric profiles and exact diameters ===")

    checked = 0
    for s in (2, 3, 4):
        for n in range(1, 6):
            universe = all_prefixes(s, n)
            # Several deterministic nontrivial projections, including singleton,
            # sparse subsets, and the full finite causal layer.
            projections = [
                universe[:1],
                universe[:: max(1, len(universe) // min(len(universe), 7))],
                universe[-min(len(universe), 5) :],
                universe,
            ]
            for projection in projections:
                projection = finite_projection(projection)
                rho_values = delta_rho_profile(projection)
                direct_rho_values = {p.delta_rho for p in projection}
                assert rho_values == direct_rho_values

                rho_diam = delta_rho_diameter(projection)
                assert rho_diam == max(rho_values) - min(rho_values)
                assert rho_diam == max(abs(a - b) for a in rho_values for b in rho_values)
                assert Fraction(0) <= rho_diam < Fraction(1)

                r_values = r_profile(projection)
                assert len(r_values) == len({p.digit_coordinate for p in projection})

                d_min = min(p.digit_coordinate for p in projection)
                d_max = max(p.digit_coordinate for p in projection)
                expected_r_diam = log(Rational(d_max + 1, d_min + 1)) / log(s)
                assert simplify(r_diameter_expr(projection) - expected_r_diam) == 0
                assert simplify(r_diameter_expr(projection)) >= 0
                checked += 1

    expect_raises(ValueError, lambda: finite_projection(()), "empty finite projection")
    expect_raises(ValueError, lambda: StatePrefix((), 2), "empty geometric prefix")
    expect_raises(ValueError, lambda: StatePrefix((1, 3), 2), "state outside S")
    expect_raises(ValueError, lambda: finite_projection((StatePrefix((1,), 2), StatePrefix((1,), 3))), "mixed bases")
    expect_raises(ValueError, lambda: finite_projection((StatePrefix((1,), 2), StatePrefix((1, 1), 2))), "mixed levels")

    print(f"[OK] Checked {checked} finite projections over several bases and levels")
    print("[OK] Delta-rho and logarithmic profiles are exact images of finite projections")
    print("[OK] D_rho and D_r are exact finite pairwise suprema")
    print("[OK] Invalid finite projections and invalid internal-state prefixes are rejected soundly")


def verify_symbolic_logarithmic_diameter_formula() -> None:
    print("\n=== Symbolic verification of logarithmic diameter formula ===")

    s = Symbol("s", integer=True, positive=True)
    d_min = Symbol("d_min", integer=True, nonnegative=True)
    d_max = Symbol("d_max", integer=True, nonnegative=True)

    r_min = log(d_min + 1) / log(s)
    r_max = log(d_max + 1) / log(s)
    diameter = r_max - r_min
    expected = log((d_max + 1) / (d_min + 1)) / log(s)

    assert simplify(diameter - expected) == 0

    # Concrete exact substitutions avoid relying on an ordering engine for log.
    for base in range(2, 8):
        for a in range(0, 12):
            for b in range(a, 18):
                value = expected.subs({s: base, d_min: a, d_max: b})
                assert float(value) >= -1e-12
                if a == b:
                    assert simplify(value) == 0
                else:
                    assert float(value) > 0

    print("[OK] D_r = log_s((D_max+1)/(D_min+1)) follows symbolically from r=log_s(D+1)")
    print("[OK] Boundary and positivity cases were checked for exact integer coordinates")


def verify_weak_and_strong_localization_logic() -> None:
    print("\n=== Weak and strong causal-localization logic ===")

    assert STRONG_GEOMETRY.strongly_localized()
    assert STRONG_GEOMETRY.weakly_localized()

    assert WEAK_BY_RHO_ONLY.weakly_localized()
    assert not WEAK_BY_RHO_ONLY.strongly_localized()

    assert WEAK_BY_R_ONLY.weakly_localized()
    assert not WEAK_BY_R_ONLY.strongly_localized()

    assert not NONLOCAL_LOG.weakly_localized()
    assert not NONLOCAL_LOG.strongly_localized()
    assert NONLOCAL_LOG.not_localized()

    assert not NONLOCAL_SQRT.weakly_localized()
    assert NONLOCAL_SQRT.not_localized()

    assert not OSCILLATORY_NONLOCAL.weakly_localized()
    assert OSCILLATORY_NONLOCAL.not_localized()

    # Finite-shift invariance of the asymptotic regimes used by causal containment.
    for profile in (STRONG_GEOMETRY, WEAK_BY_RHO_ONLY, WEAK_BY_R_ONLY, NONLOCAL_LOG):
        for k in range(0, 10):
            shifted = profile.shifted(k)
            assert shifted.weakly_localized() == profile.weakly_localized()
            assert shifted.strongly_localized() == profile.strongly_localized()
            assert shifted.not_localized() == profile.not_localized()

    print("[OK] Weak localization is correctly verified as a disjunction")
    print("[OK] Strong localization is correctly verified as a conjunction")
    print("[OK] Strong localization implies weak localization, and the converse fails")
    print("[OK] Localization regimes are invariant under finite tail shifts")


def verify_O1_is_not_equal_slope() -> None:
    print("\n=== Verification that O(1) is not replaced by equal slope ===")

    n = Symbol("n", positive=True)
    r1 = n
    r2 = n + log(n)
    r3 = n + sqrt(n)
    r4 = n + Rational(5, 3)

    assert limit((r2 - r1), n, oo) == oo
    assert limit((r3 - r1), n, oo) == oo
    assert limit((r4 - r1), n, oo) == Rational(5, 3)

    # Same leading linear ratio does not imply bounded difference.
    assert limit(r1 / n, n, oo) == 1
    assert limit(r2 / n, n, oo) == 1
    assert limit(r3 / n, n, oo) == 1

    print("[OK] Equal leading linear slope does not imply D_r=O(1)")
    print("[OK] log(n) and sqrt(n) deviations are correctly rejected as unbounded spread")
    print("[OK] A constant offset is correctly accepted as O(1)")


def verify_loss_of_localization_equivalence() -> None:
    print("\n=== Loss of localization and logical complement of weak localization ===")

    profiles = [STRONG_GEOMETRY, WEAK_BY_RHO_ONLY, WEAK_BY_R_ONLY, NONLOCAL_LOG, NONLOCAL_SQRT, OSCILLATORY_NONLOCAL]
    for profile in profiles:
        weak = profile.weakly_localized()
        complement = profile.rho_limsup == 1 and not profile.r_is_O1
        assert (not weak) == complement, profile.name
        assert profile.not_localized() == complement

    # Exact finite values remain inside the causal range even for profiles whose
    # limsup fills the whole available interval.
    for profile in (NONLOCAL_LOG, NONLOCAL_SQRT, OSCILLATORY_NONLOCAL):
        for n_value in range(2, 60):
            value = profile.rho_diameter(n_value)
            assert Fraction(0) <= value <= Fraction(1)

    print("[OK] not weakly localized iff limsup D_rho=1 and D_r is not O(1)")
    print("[OK] Full-cone filling, unbounded logarithmic spread, and oscillatory limsup failure are detected")


def verify_causal_containment_under_refinement() -> None:
    print("\n=== Causal containment under unbounded recursive refinement ===")

    strong_tower = make_refinement_tower(geometry=STRONG_GEOMETRY)
    weak_tower = make_refinement_tower(geometry=WEAK_BY_RHO_ONLY)
    weak_r_tower = make_refinement_tower(geometry=WEAK_BY_R_ONLY)
    escaping_tower = make_refinement_tower(geometry=NONLOCAL_LOG)
    incompatible_tower = make_incompatible_tower()

    assert strong_tower.is_recursively_compatible()
    assert weak_tower.is_recursively_compatible()
    assert weak_r_tower.is_recursively_compatible()
    assert escaping_tower.is_recursively_compatible()
    assert not incompatible_tower.is_recursively_compatible()

    assert contained_in_mode([strong_tower], "strong")
    assert contained_in_mode([strong_tower], "weak")

    assert contained_in_mode([weak_tower], "weak")
    assert not contained_in_mode([weak_tower], "strong")

    assert contained_in_mode([weak_r_tower], "weak")
    assert not contained_in_mode([weak_r_tower], "strong")

    assert not contained_in_mode([escaping_tower], "weak")
    assert not contained_in_mode([incompatible_tower], "weak")

    expect_raises(ValueError, lambda: contained_in_mode([], "weak"), "empty continuation family")
    expect_raises(ValueError, lambda: contained_in_mode([strong_tower], "invalid"), "invalid containment mode")

    print("[OK] Compatible recursive-refinement towers are accepted")
    print("[OK] Incompatible one-step refinements are rejected")
    print("[OK] Weak and strong containment modes are distinguished")
    print("[OK] Escaping geometry is not causally contained")
    print("[OK] Empty continuation families are not accepted vacuously")


def verify_independence_of_stability_and_localization() -> None:
    print("\n=== Independence of recursive stability and causal localization ===")

    stable_not_local = CandidateStructure(
        name="stable invariant, nonlocalized geometry",
        recursively_stable=True,
        geometry=NONLOCAL_LOG,
        contained=False,
    )
    local_not_stable = CandidateStructure(
        name="localized geometry, unstable invariant",
        recursively_stable=False,
        geometry=STRONG_GEOMETRY,
        contained=True,
    )
    both = CandidateStructure(
        name="stable localized contained structure",
        recursively_stable=True,
        geometry=STRONG_GEOMETRY,
        contained=True,
    )
    neither = CandidateStructure(
        name="unstable nonlocalized noncontained structure",
        recursively_stable=False,
        geometry=NONLOCAL_LOG,
        contained=False,
    )

    assert stable_not_local.recursively_stable and not stable_not_local.geometry.weakly_localized()
    assert local_not_stable.geometry.strongly_localized() and not local_not_stable.recursively_stable
    assert both.localized_recursively_stable("strong")
    assert both.localized_recursively_stable("weak")
    assert not neither.localized_recursively_stable("weak")

    print("[OK] Recursive stability does not imply causal localization")
    print("[OK] Causal localization does not imply recursive stability")
    print("[OK] The conjunction can be satisfied, and can also fail completely")


def verify_localized_recursively_stable_structure_conjunction() -> None:
    print("\n=== Localized recursively stable structure as a genuine conjunction ===")

    valid = CandidateStructure("valid", True, STRONG_GEOMETRY, True)
    missing_stability = CandidateStructure("missing stability", False, STRONG_GEOMETRY, True)
    missing_localization = CandidateStructure("missing localization", True, NONLOCAL_LOG, True)
    missing_containment = CandidateStructure("missing containment", True, STRONG_GEOMETRY, False)
    weak_not_strong = CandidateStructure("weak but not strong", True, WEAK_BY_R_ONLY, True)

    assert valid.localized_recursively_stable("weak")
    assert valid.localized_recursively_stable("strong")

    assert not missing_stability.localized_recursively_stable("weak")
    assert not missing_localization.localized_recursively_stable("weak")
    assert not missing_containment.localized_recursively_stable("weak")

    assert weak_not_strong.localized_recursively_stable("weak")
    assert not weak_not_strong.localized_recursively_stable("strong")

    print("[OK] All three defining clauses are necessary")
    print("[OK] Weakly localized stable containment is distinguished from strongly localized stable containment")


def verify_emergent_boundary_as_loss_of_recursive_compatibility() -> None:
    print("\n=== Boundary as loss of recursive compatibility/admissibility ===")

    def admissible(prefix: StatePrefix, center: Fraction, radius: Fraction, max_digit: int) -> bool:
        return abs(prefix.delta_rho - center) <= radius and prefix.digit_coordinate <= max_digit

    center = Fraction(0)
    radius = Fraction(1, 8)
    max_digit = 3

    level_3 = all_prefixes(2, 3)
    admissible_level_3 = tuple(p for p in level_3 if admissible(p, center, radius, max_digit))
    rejected_level_3 = tuple(p for p in level_3 if not admissible(p, center, radius, max_digit))

    assert admissible_level_3
    assert rejected_level_3
    assert set(admissible_level_3).isdisjoint(rejected_level_3)
    assert len(admissible_level_3) + len(rejected_level_3) == len(level_3)

    next_candidates = all_prefixes(2, 4)
    compatible_next = tuple(
        p for p in next_candidates if p.parent() in set(admissible_level_3) and admissible(p, center, radius, max_digit)
    )
    boundary_failures = tuple(
        p
        for p in next_candidates
        if p.parent() in set(admissible_level_3) and not admissible(p, center, radius, max_digit)
    )

    assert compatible_next
    assert boundary_failures
    for p in boundary_failures:
        assert p.parent() in set(admissible_level_3)
        assert not admissible(p, center, radius, max_digit)

    # The boundary changes when the organization predicate changes, so it is not
    # a fixed external cut imposed independently of the recursive structure.
    larger_radius = Fraction(1, 4)
    enlarged_admissible = tuple(p for p in level_3 if admissible(p, center, larger_radius, max_digit))
    assert set(admissible_level_3).issubset(set(enlarged_admissible))
    assert len(enlarged_admissible) > len(admissible_level_3)

    print("[OK] Accepted region is exactly the recursively compatible admissible region")
    print("[OK] Boundary failures are compatible refinements that leave the controlled geometric profile")
    print("[OK] Changing the organization predicate changes the boundary, so no fixed external cut is used")


def verify_geometric_localization_does_not_fix_internal_organization() -> None:
    print("\n=== Geometric localization versus internal-state organization ===")

    organized = InternalOrganization(
        name="geometrically localized and internally convergent",
        geometric_data=STRONG_GEOMETRY,
        internal_frequency_limit=Fraction(1, 2),
        internal_frequency_convergent=True,
    )
    blurred_limit = InternalOrganization(
        name="same geometry but different internal limit",
        geometric_data=STRONG_GEOMETRY,
        internal_frequency_limit=Fraction(1, 3),
        internal_frequency_convergent=True,
    )
    nonconvergent_internal = InternalOrganization(
        name="same geometry but nonconvergent internal frequencies",
        geometric_data=STRONG_GEOMETRY,
        internal_frequency_limit=None,
        internal_frequency_convergent=False,
    )

    assert organized.passes_geometric_localization()
    assert blurred_limit.passes_geometric_localization()
    assert nonconvergent_internal.passes_geometric_localization()

    assert organized.passes_internal_organization()
    assert blurred_limit.passes_internal_organization()
    assert organized.internal_frequency_limit != blurred_limit.internal_frequency_limit
    assert not nonconvergent_internal.passes_internal_organization()

    print("[OK] Identical geometric localization data can coexist with different internal-state frequency data")
    print("[OK] Geometric localization alone does not enforce internal-state organization")
    print("[OK] Nonconvergent internal organization is invisible to the geometric localization predicate")


def verify_exact_examples_of_rho_spread_inside_causal_cone() -> None:
    print("\n=== Exact examples of causal-cone spread and localization regimes ===")

    # Strong finite family: two prefixes whose normalized spread tends to zero
    # while logarithmic spread remains bounded.
    for n in range(4, 18):
        left = StatePrefix(tuple([1] * n), 2)
        near_left = StatePrefix(tuple([1] * (n - 2) + [2, 2]), 2)
        projection = (left, near_left)
        rho_spread = delta_rho_diameter(projection)
        r_spread = r_diameter_expr(projection)
        assert rho_spread == Fraction(3, 2**n)
        assert simplify(r_spread - log(4) / log(2)) == 0

    # Full-cone finite family: the leftmost and rightmost prefixes fill almost
    # the whole normalized coordinate range, and logarithmic spread grows.
    for n in range(2, 12):
        left = StatePrefix(tuple([1] * n), 2)
        right = StatePrefix(tuple([2] * n), 2)
        projection = (left, right)
        rho_spread = delta_rho_diameter(projection)
        assert rho_spread == Fraction(2**n - 1, 2**n)
        assert simplify(r_diameter_expr(projection) - n) == 0

    print("[OK] Strong finite witnesses have D_rho -> 0 and bounded D_r")
    print("[OK] Full-cone finite witnesses have D_rho -> 1 and unbounded D_r")


def main() -> None:
    if not __debug__:
        raise RuntimeError(
            "This verification script must be run without Python optimization (-O), "
            "because assertions are part of the verification."
        )
    
    print("=== Verification of causal localization and containment of stable recursive structures ===")
    verify_finite_geometric_profiles_and_diameters()
    verify_symbolic_logarithmic_diameter_formula()
    verify_weak_and_strong_localization_logic()
    verify_O1_is_not_equal_slope()
    verify_loss_of_localization_equivalence()
    verify_causal_containment_under_refinement()
    verify_independence_of_stability_and_localization()
    verify_localized_recursively_stable_structure_conjunction()
    verify_emergent_boundary_as_loss_of_recursive_compatibility()
    verify_geometric_localization_does_not_fix_internal_organization()
    verify_exact_examples_of_rho_spread_inside_causal_cone()
    print("\n=== Causal localization verification completed successfully ===")


if __name__ == "__main__":
    main()
